# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Website of Dutchsec intern LarsTD
email: lars.boelhouwers@dutchsec.com
description: > # this means to ignore newlines until "baseurl:"
This website is made for an assignment by Dutchsec.
This is a test website but it may be an actual site later.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://larstd.github.io" # the base hostname & protocol for your site
github_username:  LarsTD

# Build settings
markdown: kramdown
